
server:
  port: 8080

spring:
  application:
    name: kafka-producer-api

  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true

      bindings:
        output-out-0:
          destination: skeleton-send-message
          content-type: application/*+avro

      kafka:
        binder:
          autoCreateTopics: true
          configuration:
            auto.register.schemas: true
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081

topic:
  name: skeleton-send-message

