
server:
  port: 8090

spring:
  application:
    name: kafka-consumer-async

  cloud:
    stream:
      default:
        consumer:
          useNativeDecoding: true

      bindings:
        messageConsumer-in-0:
          destination: skeleton-send-message
          group: my-group
          content-type: application/*+avro

      kafka:
        binder:
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true

remote:
  external-service-api:
    url: http://localhost:8091

topic:
  name: skeleton-send-message
